apps/authentication/urls.py
from django.urls import path

from . import views
from . import interactors


app_name = "authentication"


# Views

urlpatterns = [
    path("authentication-view/", views.authentication, name="authentication_view"),
]

# Interactors

urlpatterns += [
    path("signup/", interactors.signup, name="signup"),
    path("signin/", interactors.signin, name="signin"),
    path("signout/", interactors.signout, name="signout"),
]

apps/diaries/urls.py
from django.urls import path

from . import views
from . import interactors


app_name = "diaries"


# Views

urlpatterns = [
    path("diaries-view/", views.diaries, name="diaries_view"),
    path("newsfeed-view/", views.newsfeed, name="newsfeed_view"),
    path("<int:id>/detail-view/", views.detail, name="detail_view")
]

# Interactors

urlpatterns += [
    path('<int:diary_id>/commit/', interactors.create_commit, name="commit"),
    path('<int:diary_id>/comment/', interactors.create_comment, name="comment"),
    # path('<int:id>/update/', interactors.update, name="update"),
]

apps/issues/urls.py
from django.urls import path

from . import views
from . import interactors


app_name = "issues"


# Views

urlpatterns = [
    path("issues-view", views.issues, name="issues_view"),
    path("create-view", views.create, name="create_view")
]

# Interactors

urlpatterns += [
    path('create/', interactors.create, name="create"),
    # path('<int:id>/update/', interactors.update, name="update"),
]

rp2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


def default_view(request):
    return redirect("clans:overview")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("authentication/", include("apps.authentication.urls", namespace="authentication")),
    path("accounts/", include("apps.accounts.urls", namespace="accounts")),
    path("issues/", include("apps.issues.urls", namespace="issues")),
    path("clans/", include("apps.clans.urls", namespace="clans")),
    path("diaries/", include("apps.diaries.urls", namespace="diaries")),
    path("", default_view),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/partials/expanded-left-sidebar.html
{% load static %}

<nav id="navigation-widget" class="navigation-widget navigation-widget-desktop sidebar left hidden" data-simplebar>
    <!-- NAVIGATION WIDGET COVER -->
    <figure class="navigation-widget-cover liquid">
        <img src="{% static 'img/cover/01.jpg' %}" alt="cover-01">
    </figure>
    <!-- /NAVIGATION WIDGET COVER -->

    <!-- USER SHORT DESCRIPTION -->
    <div class="user-short-description">
        <!-- USER SHORT DESCRIPTION AVATAR -->
        <a class="user-short-description-avatar user-avatar medium" href="#">
            <!-- USER AVATAR BORDER -->
            <div class="user-avatar-border">
                <!-- HEXAGON -->
                <div class="hexagon-120-132"></div>
                <!-- /HEXAGON -->
            </div>
            <!-- /USER AVATAR BORDER -->

            <!-- USER AVATAR CONTENT -->
            <div class="user-avatar-content">
                <!-- HEXAGON -->
                <div class="hexagon-image-82-90" data-src="{% static 'img/badge/gold-b.png' %}"></div>
                <!-- /HEXAGON -->
            </div>
            <!-- /USER AVATAR CONTENT -->

            <!-- USER AVATAR PROGRESS -->
            <div class="user-avatar-progress">
              <!-- HEXAGON -->
              <div class="hexagon-progress-100-110 logged-account-hexagon-progress-100-110"></div>
              <!-- /HEXAGON -->
            </div>
            <!-- /USER AVATAR PROGRESS -->

            <!-- USER AVATAR PROGRESS BORDER -->
            <div class="user-avatar-progress-border">
                <!-- HEXAGON -->
                <div class="hexagon-border-100-110"></div>
                <!-- /HEXAGON -->
            </div>
            <!-- /USER AVATAR PROGRESS BORDER -->

            <!-- USER AVATAR BADGE -->
            <div class="user-avatar-badge">
                <!-- USER AVATAR BADGE BORDER -->
                <div class="user-avatar-badge-border">
                    <!-- HEXAGON -->
                    <div class="hexagon-32-36"></div>
                    <!-- /HEXAGON -->
                </div>
                <!-- /USER AVATAR BADGE BORDER -->

                <!-- USER AVATAR BADGE CONTENT -->
                <div class="user-avatar-badge-content">
                    <!-- HEXAGON -->
                    <div class="hexagon-dark-26-28"></div>
                    <!-- /HEXAGON -->
                </div>
                <!-- /USER AVATAR BADGE CONTENT -->

                <!-- USER AVATAR BADGE TEXT -->
                <p class="user-avatar-badge-text">{{ user.account.level }}</p>
                <!-- /USER AVATAR BADGE TEXT -->
            </div>
            <!-- /USER AVATAR BADGE -->
        </a>
        <!-- /USER SHORT DESCRIPTION AVATAR -->

        <!-- USER SHORT DESCRIPTION TITLE -->
        <p class="user-short-description-title"><a href="#">{{ user.first_name }} {{ user.last_name }}</a></p>
        <!-- /USER SHORT DESCRIPTION TITLE -->

        <!-- USER SHORT DESCRIPTION TEXT -->
        <p class="user-short-description-text">
            <a href="#">
                {% if user.account.clan %}
                    {{ user.account.clan }}
                {% else %}
                    No Clan
                {% endif %}
            </a>
        </p>
        <!-- /USER SHORT DESCRIPTION TEXT -->
    </div>
    <!-- /USER SHORT DESCRIPTION -->

    <!-- BADGE LIST --><!-- /BADGE LIST -->

    <!-- USER STATS --><!-- /USER STATS -->

    <!-- MENU -->
    <ul class="menu">

        <!-- MENU ITEM -->
        <li class="menu-item {% if request.resolver_match.url_name == 'overview' %} active {% endif %}">
            <!-- MENU ITEM LINK -->
            <a class="menu-item-link" href="{% url 'clans:overview' %}">
                <!-- MENU ITEM LINK ICON -->
                <svg class="menu-item-link-icon icon-newsfeed">
                    <use xlink:href="#svg-overview"></use>
                </svg>
                <!-- /MENU ITEM LINK ICON -->
                Overview
            </a>
            <!-- /MENU ITEM LINK -->
        </li>
        <!-- /MENU ITEM -->

        <!-- MENU ITEM -->
        <li class="menu-item {% if request.resolver_match.url_name == 'newsfeed_view' %} active {% endif %}">
            <!-- MENU ITEM LINK -->
            <a class="menu-item-link" href="{% url 'diaries:newsfeed_view' %}">
                <!-- MENU ITEM LINK ICON -->
                <svg class="menu-item-link-icon icon-newsfeed">
                    <use xlink:href="#svg-group"></use>
                </svg>
                <!-- /MENU ITEM LINK ICON -->
                Newsfeed
            </a>
            <!-- /MENU ITEM LINK -->
        </li>
        <!-- /MENU ITEM -->

        <!-- MENU ITEM -->
        <li class="menu-item {% if request.resolver_match.url_name == 'diaries_view' %} active {% endif %}">
            <!-- MENU ITEM LINK -->
            <a class="menu-item-link" href="{% url 'diaries:diaries_view' %}">
                <!-- MENU ITEM LINK ICON -->
                <svg class="menu-item-link-icon icon-newsfeed">
                    <use xlink:href="#svg-events"></use>
                </svg>
                <!-- /MENU ITEM LINK ICON -->
                My Diaries
            </a>
            <!-- /MENU ITEM LINK -->
        </li>
        <!-- /MENU ITEM -->

<!--        &lt;!&ndash; MENU ITEM &ndash;&gt;-->
<!--        <li class="menu-item">-->
<!--            &lt;!&ndash; MENU ITEM LINK &ndash;&gt;-->
<!--            <a class="menu-item-link" href="{% url 'issues:issues_view' %}">-->
<!--                &lt;!&ndash; MENU ITEM LINK ICON &ndash;&gt;-->
<!--                <svg class="menu-item-link-icon icon-newsfeed">-->
<!--                    <use xlink:href="#svg-overview"></use>-->
<!--                </svg>-->
<!--                &lt;!&ndash; /MENU ITEM LINK ICON &ndash;&gt;-->
<!--                Issues-->
<!--            </a>-->
<!--            &lt;!&ndash; /MENU ITEM LINK &ndash;&gt;-->
<!--        </li>-->
<!--        &lt;!&ndash; /MENU ITEM &ndash;&gt;-->

        <!-- MENU ITEM -->
        <li class="menu-item">
            <!-- MENU ITEM LINK -->
            <a class="menu-item-link" href="{% url 'authentication:signout' %}">
                <!-- MENU ITEM LINK ICON -->
                <svg class="menu-item-link-icon icon-newsfeed">
                    <use xlink:href="#svg-login"></use>
                </svg>
                <!-- /MENU ITEM LINK ICON -->
                Signout
            </a>
            <!-- /MENU ITEM LINK -->
        </li>
        <!-- /MENU ITEM -->

    </ul>
    <!-- /MENU -->
</nav>

templates/partials/header.html
{% load static %}

<header class="header">
    <!-- HEADER ACTIONS -->
    <div class="header-actions">
      <!-- HEADER BRAND -->
      <div class="header-brand">
        <!-- LOGO -->
        <div class="logo">
          <!-- ICON LOGO VIKINGER -->
          <svg class="icon-logo-vikinger small">
            <use xlink:href="#svg-logo-vikinger"></use>
          </svg>
          <!-- /ICON LOGO VIKINGER -->
        </div>
        <!-- /LOGO -->

        <!-- HEADER BRAND TEXT -->
        <h1 class="header-brand-text">RP2</h1>
        <!-- /HEADER BRAND TEXT -->
      </div>
      <!-- /HEADER BRAND -->
    </div>
    <!-- /HEADER ACTIONS -->

    <!-- HEADER ACTIONS -->
    <div class="header-actions">
      <!-- SIDEMENU TRIGGER -->
      <div class="sidemenu-trigger navigation-widget-trigger">
        <!-- ICON GRID -->
        <svg class="icon-grid">
          <use xlink:href="#svg-grid"></use>
        </svg>
        <!-- /ICON GRID -->
      </div>
      <!-- /SIDEMENU TRIGGER -->

      <!-- MOBILEMENU TRIGGER -->
      <div class="mobilemenu-trigger navigation-widget-mobile-trigger">
        <!-- BURGER ICON -->
        <div class="burger-icon inverted">
          <!-- BURGER ICON BAR -->
          <div class="burger-icon-bar"></div>
          <!-- /BURGER ICON BAR -->

          <!-- BURGER ICON BAR -->
          <div class="burger-icon-bar"></div>
          <!-- /BURGER ICON BAR -->

          <!-- BURGER ICON BAR -->
          <div class="burger-icon-bar"></div>
          <!-- /BURGER ICON BAR -->
        </div>
        <!-- /BURGER ICON -->
      </div>
      <!-- /MOBILEMENU TRIGGER -->

      <!-- NAVIGATION -->
      <nav class="navigation">
        <!-- MENU MAIN -->
        <ul class="menu-main">

          <!-- MENU MAIN ITEM -->
          <li class="menu-main-item">
            <!-- MENU MAIN ITEM LINK -->
            <a class="menu-main-item-link" href="{% url 'diaries:newsfeed_view' %}">Newsfeed</a>
            <!-- /MENU MAIN ITEM LINK -->
          </li>
          <!-- /MENU MAIN ITEM -->

          <!-- MENU MAIN ITEM -->
          <li class="menu-main-item">
            <!-- MENU MAIN ITEM LINK -->
            <a class="menu-main-item-link" href="#">FAQs</a>
            <!-- /MENU MAIN ITEM LINK -->
          </li>
          <!-- /MENU MAIN ITEM -->

        </ul>
        <!-- /MENU MAIN -->
      </nav>
      <!-- /NAVIGATION -->
    </div>
    <!-- /HEADER ACTIONS -->

    <!-- HEADER ACTIONS -->
    <div class="header-actions search-bar">
      <!-- INTERACTIVE INPUT --><!-- /INTERACTIVE INPUT -->
      <!-- DROPDOWN BOX --><!-- /DROPDOWN BOX -->
    </div>
    <!-- /HEADER ACTIONS -->

    <!-- HEADER ACTIONS -->
    <div class="header-actions">
      <!-- PROGRESS STAT -->
      <div class="progress-stat">
        <!-- BAR PROGRESS WRAP -->
        <div class="bar-progress-wrap">
          <!-- BAR PROGRESS INFO -->
          <p class="bar-progress-info">Next: <span class="bar-progress-text"></span></p>
          <!-- /BAR PROGRESS INFO -->
        </div>
        <!-- /BAR PROGRESS WRAP -->

        <!-- PROGRESS STAT BAR -->
        <div id="logged-user-level" class="progress-stat-bar"></div>
        <!-- /PROGRESS STAT BAR -->
      </div>
      <!-- /PROGRESS STAT -->
    </div>
    <!-- /HEADER ACTIONS -->

    <!-- HEADER ACTIONS -->
    <div class="header-actions">
      <!-- ACTION LIST --><!-- /ACTION LIST -->

      <!-- ACTION ITEM WRAP -->
      <div class="action-item-wrap">
        <!-- ACTION ITEM --><!-- /ACTION ITEM -->
        <!-- DROPDOWN NAVIGATION --><!-- /DROPDOWN NAVIGATION -->
      </div>
      <!-- /ACTION ITEM WRAP -->

    </div>
    <!-- /HEADER ACTIONS -->
</header>

templates/partials/mobile-left-sidebar.html
{% load static %}

<nav id="navigation-widget-mobile" class="navigation-widget navigation-widget-mobile sidebar left hidden"
     data-simplebar>
    <!-- NAVIGATION WIDGET CLOSE BUTTON -->
    <div class="navigation-widget-close-button">
        <!-- NAVIGATION WIDGET CLOSE BUTTON ICON -->
        <svg class="navigation-widget-close-button-icon icon-back-arrow">
            <use xlink:href="#svg-back-arrow"></use>
        </svg>
        <!-- NAVIGATION WIDGET CLOSE BUTTON ICON -->
    </div>
    <!-- /NAVIGATION WIDGET CLOSE BUTTON -->

    <!-- NAVIGATION WIDGET INFO WRAP -->
    <div class="navigation-widget-info-wrap">
        <!-- NAVIGATION WIDGET INFO -->
        <div class="navigation-widget-info">
            <!-- USER AVATAR -->
            <a class="user-avatar small no-outline" href="#">
                <!-- USER AVATAR CONTENT -->
                <div class="user-avatar-content">
                    <!-- HEXAGON -->
                    <div class="hexagon-image-30-32" data-src="{% static 'img/badge/gold-b.png' %}"></div>
                    <!-- /HEXAGON -->
                </div>
                <!-- /USER AVATAR CONTENT -->

                <!-- USER AVATAR PROGRESS --><!-- /USER AVATAR PROGRESS -->

                <!-- USER AVATAR PROGRESS BORDER -->
                <div class="user-avatar-progress-border">
                    <!-- HEXAGON -->
                    <div class="hexagon-border-40-44 logged-account-hexagon-progress-40-44"></div>
                    <!-- /HEXAGON -->
                </div>
                <!-- /USER AVATAR PROGRESS BORDER -->

                <!-- USER AVATAR BADGE -->
                <div class="user-avatar-badge">
                    <!-- USER AVATAR BADGE BORDER -->
                    <div class="user-avatar-badge-border">
                        <!-- HEXAGON -->
                        <div class="hexagon-22-24"></div>
                        <!-- /HEXAGON -->
                    </div>
                    <!-- /USER AVATAR BADGE BORDER -->

                    <!-- USER AVATAR BADGE CONTENT -->
                    <div class="user-avatar-badge-content">
                        <!-- HEXAGON -->
                        <div class="hexagon-dark-16-18"></div>
                        <!-- /HEXAGON -->
                    </div>
                    <!-- /USER AVATAR BADGE CONTENT -->

                    <!-- USER AVATAR BADGE TEXT -->
                    <p class="user-avatar-badge-text">{{ user.account.level }}</p>
                    <!-- /USER AVATAR BADGE TEXT -->
                </div>
                <!-- /USER AVATAR BADGE -->
            </a>
            <!-- /USER AVATAR -->

            <!-- NAVIGATION WIDGET INFO TITLE -->
            <p class="navigation-widget-info-title">
                <a href="#">{{ user.first_name }} {{ user.last_name }}</a>
            </p>
            <!-- /NAVIGATION WIDGET INFO TITLE -->

            <!-- NAVIGATION WIDGET INFO TEXT -->
            <p class="navigation-widget-info-text">
                <a href="#">
                    {% if user.account.clan %}
                    {{ user.account.clan }}
                    {% else %}
                    No Clan
                    {% endif %}
                </a>
            </p>
            <!-- /NAVIGATION WIDGET INFO TEXT -->
        </div>
        <!-- /NAVIGATION WIDGET INFO -->

        <!-- NAVIGATION WIDGET BUTTON -->
        <a href="{% url 'authentication:signout' %}">
            <p class="navigation-widget-info-button button small secondary">Signout</p>
        </a>
        <!-- /NAVIGATION WIDGET BUTTON -->
    </div>
    <!-- /NAVIGATION WIDGET INFO WRAP -->

    <!-- NAVIGATION WIDGET SECTION TITLE -->
    <p class="navigation-widget-section-title">Sections</p>
    <!-- /NAVIGATION WIDGET SECTION TITLE -->

    <!-- MENU -->
    <ul class="menu">

        <!-- MENU ITEM -->
        <li class="menu-item {% if request.resolver_match.url_name == 'overview' %} active {% endif %}">
            <!-- MENU ITEM LINK -->
            <a class="menu-item-link" href="{% url 'clans:overview' %}">
                <!-- MENU ITEM LINK ICON -->
                <svg class="menu-item-link-icon icon-newsfeed">
                    <use xlink:href="#svg-overview"></use>
                </svg>
                <!-- /MENU ITEM LINK ICON -->
                Overview
            </a>
            <!-- /MENU ITEM LINK -->
        </li>
        <!-- /MENU ITEM -->

        <!-- MENU ITEM -->
        <li class="menu-item {% if request.resolver_match.url_name == 'newsfeed_view' %} active {% endif %}">
            <!-- MENU ITEM LINK -->
            <a class="menu-item-link" href="{% url 'diaries:newsfeed_view' %}">
                <!-- MENU ITEM LINK ICON -->
                <svg class="menu-item-link-icon icon-newsfeed">
                    <use xlink:href="#svg-group"></use>
                </svg>
                <!-- /MENU ITEM LINK ICON -->
                Newsfeed
            </a>
            <!-- /MENU ITEM LINK -->
        </li>
        <!-- /MENU ITEM -->

        <!-- MENU ITEM -->
        <li class="menu-item {% if request.resolver_match.url_name == 'diaries_view' %} active {% endif %}">
            <!-- MENU ITEM LINK -->
            <a class="menu-item-link" href="{% url 'diaries:diaries_view' %}">
                <!-- MENU ITEM LINK ICON -->
                <svg class="menu-item-link-icon icon-newsfeed">
                    <use xlink:href="#svg-events"></use>
                </svg>
                <!-- /MENU ITEM LINK ICON -->
                My Diaries
            </a>
            <!-- /MENU ITEM LINK -->
        </li>
        <!-- /MENU ITEM -->

<!--        &lt;!&ndash; MENU ITEM &ndash;&gt;-->
<!--        <li class="menu-item">-->
<!--            &lt;!&ndash; MENU ITEM LINK &ndash;&gt;-->
<!--            <a class="menu-item-link" href="{% url 'issues:issues_view' %}">-->
<!--                &lt;!&ndash; MENU ITEM LINK ICON &ndash;&gt;-->
<!--                <svg class="menu-item-link-icon icon-newsfeed">-->
<!--                    <use xlink:href="#svg-overview"></use>-->
<!--                </svg>-->
<!--                &lt;!&ndash; /MENU ITEM LINK ICON &ndash;&gt;-->
<!--                Issues-->
<!--            </a>-->
<!--            &lt;!&ndash; /MENU ITEM LINK &ndash;&gt;-->
<!--        </li>-->
<!--        &lt;!&ndash; /MENU ITEM &ndash;&gt;-->

    </ul>
    <!-- /MENU -->

    <!-- NAVIGATION WIDGET SECTION TITLE --><!-- /NAVIGATION WIDGET SECTION TITLE -->
    <!-- NAVIGATION WIDGET SECTION LINK --><!-- /NAVIGATION WIDGET SECTION LINK -->
</nav>

templates/partials/right-sidebar.html
{% load static %}

<aside id="chat-widget-messages" class="chat-widget closed sidebar right hidden">

    <!-- CHAT WIDGET MESSAGES -->
    <div class="chat-widget-messages" data-simplebar></div>
    <!-- /CHAT WIDGET MESSAGE -->

    <!-- CHAT WIDGET FORM -->
    <form class="chat-widget-form">
      <!-- INTERACTIVE INPUT --><!-- /INTERACTIVE INPUT -->
    </form>
    <!-- /CHAT WIDGET FORM -->

    <!-- CHAT WIDGET BUTTON -->
    <div class="chat-widget-button">
      <!-- CHAT WIDGET BUTTON ICON --><!-- /CHAT WIDGET BUTTON ICON -->
      <!-- CHAT WIDGET BUTTON TEXT --><!-- /CHAT WIDGET BUTTON TEXT -->
    </div>
    <!-- /CHAT WIDGET BUTTON -->

</aside>

templates/partials/shrunk-left-sidebar.html
{% load static %}

<nav id="navigation-widget-small" class="navigation-widget navigation-widget-desktop closed sidebar left delayed">
    <!-- USER AVATAR -->
    {% include "includes/account-avatar-small.html" with account=user.account %}
    <!-- /USER AVATAR -->

    <!-- MENU -->
    <ul class="menu small">

        <!-- MENU ITEM -->
        <li class="menu-item {% if request.resolver_match.url_name == 'overview' %} active {% endif %}">
            <!-- MENU ITEM LINK -->
            <a class="menu-item-link text-tooltip-tfr" href="{% url 'clans:overview' %}"
               data-title="Overview">
                <!-- MENU ITEM LINK ICON -->
                <svg class="menu-item-link-icon icon-newsfeed">
                    <use xlink:href="#svg-overview"></use>
                </svg>
                <!-- /MENU ITEM LINK ICON -->
            </a>
            <!-- /MENU ITEM LINK -->
        </li>
        <!-- /MENU ITEM -->

        <!-- MENU ITEM -->
        <li class="menu-item {% if request.resolver_match.url_name == 'newsfeed_view' %} active {% endif %}">
            <!-- MENU ITEM LINK -->
            <a class="menu-item-link text-tooltip-tfr" href="{% url 'diaries:newsfeed_view' %}"
               data-title="Newsfeed">
                <!-- MENU ITEM LINK ICON -->
                <svg class="menu-item-link-icon icon-newsfeed">
                    <use xlink:href="#svg-group"></use>
                </svg>
                <!-- /MENU ITEM LINK ICON -->
            </a>
            <!-- /MENU ITEM LINK -->
        </li>
        <!-- /MENU ITEM -->

        <!-- MENU ITEM -->
        <li class="menu-item {% if request.resolver_match.url_name == 'diaries_view' %} active {% endif %}">
            <!-- MENU ITEM LINK -->
            <a class="menu-item-link text-tooltip-tfr" href="{% url 'diaries:diaries_view' %}"
               data-title="My Diaries">
                <!-- MENU ITEM LINK ICON -->
                <svg class="menu-item-link-icon icon-newsfeed">
                    <use xlink:href="#svg-events"></use>
                </svg>
                <!-- /MENU ITEM LINK ICON -->
            </a>
            <!-- /MENU ITEM LINK -->
        </li>
        <!-- /MENU ITEM -->

<!--        &lt;!&ndash; MENU ITEM &ndash;&gt;-->
<!--        <li class="menu-item {% if request.resolver_match.url_name == 'issues_view' %} active {% endif %}">-->
<!--            &lt;!&ndash; MENU ITEM LINK &ndash;&gt;-->
<!--            <a class="menu-item-link text-tooltip-tfr" href="{% url 'issues:issues_view' %}" data-title="Issues">-->
<!--                &lt;!&ndash; MENU ITEM LINK ICON &ndash;&gt;-->
<!--                <svg class="menu-item-link-icon icon-newsfeed">-->
<!--                    <use xlink:href="#svg-overview"></use>-->
<!--                </svg>-->
<!--                &lt;!&ndash; /MENU ITEM LINK ICON &ndash;&gt;-->
<!--            </a>-->
<!--            &lt;!&ndash; /MENU ITEM LINK &ndash;&gt;-->
<!--        </li>-->
<!--        &lt;!&ndash; /MENU ITEM &ndash;&gt;-->

        <!-- MENU ITEM -->
        <li class="menu-item">
            <!-- MENU ITEM LINK -->
            <a class="menu-item-link text-tooltip-tfr" href="{% url 'authentication:signout' %}" data-title="Logout">
                <!-- MENU ITEM LINK ICON -->
                <svg class="menu-item-link-icon icon-newsfeed">
                    <use xlink:href="#svg-login"></use>
                </svg>
                <!-- /MENU ITEM LINK ICON -->
            </a>
            <!-- /MENU ITEM LINK -->
        </li>
        <!-- /MENU ITEM -->

    </ul>
    <!-- /MENU -->

</nav>