apps/issues/urls.py
from django.urls import path

from . import views
from . import interactors


app_name = "issues"


# Views

urlpatterns = [
    path("issues-view", views.issues, name="issues_view"),
    path("create-view", views.create, name="create_view")
]

# Interactors

urlpatterns += [
    path('create/', interactors.create, name="create"),
    # path('<int:id>/update/', interactors.update, name="update"),
]

rp2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


def default_view(request):
    return redirect("clans:overview")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("authentication/", include("apps.authentication.urls", namespace="authentication")),
    path("accounts/", include("apps.accounts.urls", namespace="accounts")),
    path("issues/", include("apps.issues.urls", namespace="issues")),
    path("clans/", include("apps.clans.urls", namespace="clans")),
    path("diaries/", include("apps.diaries.urls", namespace="diaries")),
    path("", default_view),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/issues/models.py
from django.db import models
from django.utils import timezone

from apps.accounts.models import Account
from apps.clans.models import Clan


class Issue(models.Model):

    author = models.ForeignKey(Account, on_delete=models.SET_NULL, blank=True, null=True)
    assignees = models.ManyToManyField(Account, related_name="issues_from_assignee")
    reviewers = models.ManyToManyField(Account, related_name="issues_from_reviewer")
    clan = models.ForeignKey(Clan, on_delete=models.SET_NULL, blank=True, null=True)
    title = models.CharField(max_length=255, blank=False, null=False)
    category = models.CharField(max_length=64, blank=True, null=True)
    priority = models.CharField(max_length=64, blank=True, null=True)
    status = models.CharField(max_length=64, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created_date = models.DateField(default=timezone.now)
    is_closed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

apps/issues/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from rp2.pagination import paginate

from ..issues.models import Issue


@login_required
def issues(request):

    # ===== DTO

    page = request.GET.get("page", None)
    page_size = request.GET.get("page_size", None)
    title = request.GET.get("title", "")

    # ===== PROCESS

    account = request.user.account
    issue_queryset = (
        Issue.objects
        .filter(
            clan=account.clan,
            title__icontains=title,
        )
        .order_by("-id")
    )
    paginated_issue_queryset = paginate(issue_queryset, page, page_size)

    # ===== CONTEXT

    context = {
        "issues": paginated_issue_queryset,
    }

    return render(request, "issues/issues.html", context)


@login_required
def create(request):
    return render(request, "issues/create.html")

templates/issues/create.html
{% extends "base/main.html" %}
{% load static %}

{% block content %}
<div class="content-grid">

    <div class="account-hub-content">
      <!-- SECTION HEADER -->
      <div class="section-header">
      <!-- SECTION HEADER INFO -->
          <div class="section-header-info">
              <!-- SECTION PRETITLE -->
              <p class="section-pretitle">Issues</p>
              <!-- /SECTION PRETITLE -->

              <!-- SECTION TITLE -->
              <h2 class="section-title">Create Issue</h2>
              <!-- /SECTION TITLE -->
          </div>
          <!-- /SECTION HEADER INFO -->
      </div>
      <!-- /SECTION HEADER -->
    </div>

    <div class="popup-box-content limited" data-simplebar>
        <!-- WIDGET BOX -->
        <div class="widget-box">
          <!-- WIDGET BOX TITLE -->
          <p class="widget-box-title">Issue Form</p>
          <!-- /WIDGET BOX TITLE -->

          <!-- WIDGET BOX CONTENT -->
          <div class="widget-box-content">
            <!-- FORM -->
            <form class="form" action="{% url 'issues:create' %}" method="POST">
              {% csrf_token %}
              <!-- FORM ROW -->
              <div class="form-row">
                <!-- FORM ITEM -->
                <div class="form-item">
                  <!-- FORM INPUT -->
                  <div class="form-input small active">
                    <label for="title">Title</label>
                    <input type="text" id="title" name="title" value="" required>
                  </div>
                  <!-- /FORM INPUT -->
                </div>
                <!-- /FORM ITEM -->
              </div>
              <!-- /FORM ROW -->

              <!-- FORM ROW -->
              <div class="form-row">
                <!-- FORM ITEM -->
                <div class="form-item">
                  <!-- FORM SELECT -->
                  <div class="form-select">
                    <label for="category">Category</label>
                    <select id="category" name="category">
                      <option value="frontend">Frontend</option>
                      <option value="backend">Backend</option>
                      <option value="devops">Devops</option>
                      <option value="ui_ux">UI/UX</option>
                    </select>
                    <!-- FORM SELECT ICON -->
                    <svg class="form-select-icon icon-small-arrow">
                      <use xlink:href="#svg-small-arrow"></use>
                    </svg>
                    <!-- /FORM SELECT ICON -->
                  </div>
                  <!-- /FORM SELECT -->
                </div>
                <!-- /FORM ITEM -->
              </div>
              <!-- /FORM ROW -->

              <!-- FORM ROW -->
              <div class="form-row split">
                <!-- FORM ITEM -->
                <div class="form-item">
                  <!-- FORM SELECT -->
                  <div class="form-select">
                    <label for="priority">Priority</label>
                    <select id="priority" name="priority">
                      <option value="urgent">Urgent</option>
                      <option value="high">High</option>
                      <option value="medium">Medium</option>
                      <option value="low">Low</option>
                    </select>
                    <!-- FORM SELECT ICON -->
                    <svg class="form-select-icon icon-small-arrow">
                      <use xlink:href="#svg-small-arrow"></use>
                    </svg>
                    <!-- /FORM SELECT ICON -->
                  </div>
                  <!-- /FORM SELECT -->
                </div>
                <!-- /FORM ITEM -->
                <!-- FORM ITEM -->
                <div class="form-item">
                  <!-- FORM SELECT -->
                  <div class="form-select">
                    <label for="status">Status</label>
                    <select id="status" name="status">
                      <option value="todo">Todo</option>
                      <option value="in_reject">In Reject</option>
                      <option value="in_progress">In Progress</option>
                      <option value="in_review">In Review</option>
                      <option value="done">Done</option>
                    </select>
                    <!-- FORM SELECT ICON -->
                    <svg class="form-select-icon icon-small-arrow">
                      <use xlink:href="#svg-small-arrow"></use>
                    </svg>
                    <!-- /FORM SELECT ICON -->
                  </div>
                  <!-- /FORM SELECT -->
                </div>
                <!-- /FORM ITEM -->
              </div>
              <!-- /FORM ROW -->

              <!-- FORM ROW -->
              <div class="form-row">
                <!-- FORM ITEM -->
                <div class="form-item">
                  <!-- FORM INPUT -->
                  <div class="form-input small mid-textarea">
                    <textarea id="item-files" name="description" placeholder="Description"></textarea>
                  </div>
                  <!-- /FORM INPUT -->
                </div>
                <!-- /FORM ITEM -->
              </div>
              <!-- /FORM ROW -->

              <button type="submit" class="button primary full popup-manage-item-trigger mt-5">Create New Issue!</button>
            </form>
            <!-- /FORM -->
          </div>
          <!-- WIDGET BOX CONTENT -->
        </div>
        <!-- /WIDGET BOX -->
      </div>
      <!-- /POPUP BOX CONTENT -->

</div>
{% endblock content %}

templates/issues/issues.html
{% extends "base/main.html" %}
{% load static %}

{% block content %}
<div class="content-grid">

    <div class="account-hub-content">

        <!-- SECTION HEADER -->
        <div class="section-header">
            <!-- SECTION HEADER INFO -->
            <div class="section-header-info">
                <!-- SECTION PRETITLE -->
                <p class="section-pretitle">Issues</p>
                <!-- /SECTION PRETITLE -->

                <!-- SECTION TITLE -->
                <h2 class="section-title">My Issues</h2>
                <!-- /SECTION TITLE -->
            </div>
            <!-- /SECTION HEADER INFO -->
        </div>
        <!-- /SECTION HEADER -->

        <!-- SECTION FILTERS BAR -->
        <div class="section-filters-bar v6 v6-2">
            <!-- SECTION FILTERS BAR ACTIONS -->
            <div class="section-filters-bar-actions">
                <!-- FORM -->
                <form class="form">
                    <!-- FORM ITEM -->
                    <div class="form-item split">

                        <!-- FORM INPUT DECORATED -->
                        <div class="form-input-decorated">
                            <!-- FORM INPUT -->
                            <div class="form-input small active">
                                <label>Title</label>
                                <input type="text" name="title" value="{{ request.GET.title }}">
                            </div>
                            <!-- /FORM INPUT -->
                        </div>
                        <!-- /FORM INPUT DECORATED -->

                        <!-- BUTTON -->
                        <button class="button primary">
                            <!-- ICON MAGNIFYING GLASS -->
                            <svg class="icon-magnifying-glass">
                                <use xlink:href="#svg-magnifying-glass"></use>
                            </svg>
                            <!-- /ICON MAGNIFYING GLASS -->
                        </button>
                        <!-- /BUTTON -->
                    </div>
                    <!-- /FORM ITEM -->
                </form>
                <!-- /FORM -->
            </div>
            <!-- /SECTION FILTERS BAR ACTIONS -->

            <!-- SECTION FILTERS BAR ACTIONS -->
            <div class="section-filters-bar-actions">
                <!-- BUTTON -->
                <a href="{% url 'issues:create_view' %}" class="button secondary popup-manage-item-trigger">New
                    Issue</a>
                <!-- /BUTTON -->
            </div>
            <!-- /SECTION FILTERS BAR ACTIONS -->
        </div>
        <!-- /SECTION FILTERS BAR -->

        <!-- TABLE WRAP -->
        <div class="table-wrap" data-simplebar>
            <!-- TABLE -->
            <div class="table table-sales">
                <!-- TABLE HEADER -->
                <div class="table-header">
                    <!-- TABLE HEADER COLUMN -->
                    <div class="table-header-column">
                        <!-- TABLE HEADER TITLE -->
                        <p class="table-header-title">Author</p>
                        <!-- /TABLE HEADER TITLE -->
                    </div>
                    <!-- /TABLE HEADER COLUMN -->

                    <!-- TABLE HEADER COLUMN -->
                    <div class="table-header-column padded-left">
                        <!-- TABLE HEADER TITLE -->
                        <p class="table-header-title">Title</p>
                        <!-- /TABLE HEADER TITLE -->
                    </div>
                    <!-- /TABLE HEADER COLUMN -->

                    <!-- TABLE HEADER COLUMN -->
                    <div class="table-header-column centered padded">
                        <!-- TABLE HEADER TITLE -->
                        <p class="table-header-title">Type</p>
                        <!-- /TABLE HEADER TITLE -->
                    </div>
                    <!-- /TABLE HEADER COLUMN -->

                    <!-- TABLE HEADER COLUMN -->
                    <div class="table-header-column centered padded">
                        <!-- TABLE HEADER TITLE -->
                        <p class="table-header-title">Status</p>
                        <!-- /TABLE HEADER TITLE -->
                    </div>
                    <!-- /TABLE HEADER COLUMN -->

                    <!-- TABLE HEADER COLUMN -->
                    <div class="table-header-column centered padded">
                        <!-- TABLE HEADER TITLE -->
                        <p class="table-header-title">Priority</p>
                        <!-- /TABLE HEADER TITLE -->
                    </div>
                    <!-- /TABLE HEADER COLUMN -->

                    <!-- TABLE HEADER COLUMN -->
                    <div class="table-header-column centered padded">
                        <!-- TABLE HEADER TITLE -->
                        <p class="table-header-title">Created Date</p>
                        <!-- /TABLE HEADER TITLE -->
                    </div>
                    <!-- /TABLE HEADER COLUMN -->

                    <!-- TABLE HEADER COLUMN -->
                    <div class="table-header-column padded-left"></div>
                    <!-- /TABLE HEADER COLUMN -->
                </div>
                <!-- /TABLE HEADER -->

                <!-- TABLE BODY -->
                <div class="table-body same-color-rows">

                    {% for issue in issues %}
                    <!-- TABLE ROW -->
                    <div class="table-row micro">
                        <!-- TABLE COLUMN -->
                        <div class="table-column">
                            <!-- TABLE TEXT -->
                            <p class="table-text"><span class="light">{{ issue.author }}</span></p>
                            <!-- /TABLE TEXT -->
                        </div>
                        <!-- /TABLE COLUMN -->

                        <!-- TABLE COLUMN -->
                        <div class="table-column padded-left">
                            <!-- TABLE LINK -->
                            <a class="table-link" href="#">
                                <span class="light">{{ issue.title|truncatechars:70 }}</span>
                            </a>
                            <!-- /TABLE LINK -->
                        </div>
                        <!-- /TABLE COLUMN -->

                        <!-- TABLE COLUMN -->
                        <div class="table-column centered padded">
                            <!-- TABLE TITLE -->
                            <p class="table-text">{{ issue.category }}</p>
                            <!-- /TABLE TITLE -->
                        </div>
                        <!-- /TABLE COLUMN -->

                        <!-- TABLE COLUMN -->
                        <div class="table-column centered padded">
                            <!-- TABLE TEXT -->
                            <p class="table-title">
                                {% if issue.status == 'todo' %}
                                    <span class="btn btn-primary btn-sm">
                                        Todo
                                    </span>
                                {% elif issue.status == 'in_progress' %}
                                    <span class="btn btn-warning btn-sm">
                                        In Progress
                                    </span>
                                {% elif issue.status == 'in_reject' %}
                                    <span class="btn btn-danger btn-sm">
                                        In Reject
                                    </span>
                                {% elif issue.status == 'in_review' %}
                                    <span class="btn btn-secondary btn-sm">
                                        In Review
                                    </span>
                                {% elif issue.status == 'done' %}
                                    <span class="btn btn-success btn-sm">
                                        Done
                                    </span>
                                {% endif %}
                            </p>
                            <!-- /TABLE TEXT -->
                        </div>
                        <!-- /TABLE COLUMN -->

                        <!-- TABLE COLUMN -->
                        <div class="table-column centered padded">
                            <!-- TABLE TITLE -->
                            <p class="table-text">
                                <span>
                                    {{ issue.priority }}
                                </span>
                            </p>
                            <!-- /TABLE TITLE -->
                        </div>
                        <!-- /TABLE COLUMN -->

                        <!-- TABLE COLUMN -->
                        <div class="table-column centered padded">
                            <!-- TABLE TEXT -->
                            <p class="table-title">
                                <span class="light">{{ issue.created_date|date:"d.m.Y" }}</span>
                            </p>
                            <!-- /TABLE TEXT -->
                        </div>
                        <!-- /TABLE COLUMN -->

                        <!-- TABLE COLUMN -->
                        <div class="table-column padded-left">
                            {% if issue.is_closed %}
                            <!-- PERCENTAGE DIFF ICON WRAP -->
                            <div class="percentage-diff-icon-wrap positive">
                                <!-- PERCENTAGE DIFF ICON -->
                                <svg class="percentage-diff-icon icon-plus-small">
                                    <use xlink:href="#svg-check"></use>
                                </svg>
                            </div>
                            {% else %}
                            <div class="percentage-diff-icon-wrap negative">
                                <svg class="percentage-diff-icon icon-plus-small">
                                    <use xlink:href="#svg-minus-small"></use>
                                </svg>
                            </div>
                            {% endif %}
                            <!-- /PERCENTAGE DIFF ICON -->
                        </div>
                        <!-- /PERCENTAGE DIFF ICON WRAP -->
                    </div>
                    {% endfor %}
                    <!-- /TABLE COLUMN -->

                </div>
                <!-- /TABLE ROW -->

            </div>
            <!-- /TABLE BODY -->
        </div>
        <!-- /TABLE -->
    </div>
    <!-- /TABLE WRAP -->

    <!-- SECTION PAGER BAR WRAP -->
    {% include "includes/pager-bar.html" with objects=issues %}
    <!-- /SECTION PAGER BAR WRAP -->

</div>
{% endblock content %}