apps/diaries/urls.py
from django.urls import path

from . import views
from . import interactors


app_name = "diaries"


# Views

urlpatterns = [
    path("diaries-view/", views.diaries, name="diaries_view"),
    path("newsfeed-view/", views.newsfeed, name="newsfeed_view"),
    path("<int:id>/detail-view/", views.detail, name="detail_view")
]

# Interactors

urlpatterns += [
    path('<int:diary_id>/commit/', interactors.create_commit, name="commit"),
    path('<int:diary_id>/comment/', interactors.create_comment, name="comment"),
    # path('<int:id>/update/', interactors.update, name="update"),
]

rp2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


def default_view(request):
    return redirect("clans:overview")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("authentication/", include("apps.authentication.urls", namespace="authentication")),
    path("accounts/", include("apps.accounts.urls", namespace="accounts")),
    path("issues/", include("apps.issues.urls", namespace="issues")),
    path("clans/", include("apps.clans.urls", namespace="clans")),
    path("diaries/", include("apps.diaries.urls", namespace="diaries")),
    path("", default_view),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/account-avatar-small.html
{% load static %}
{% load level_design %}

<!-- USER AVATAR -->
<!--  add 'online' class below if user online  -->
<div class="user-avatar small no-outline">
    <!-- USER AVATAR CONTENT -->
    <div class="user-avatar-content">
        <!-- HEXAGON -->
        <div class="hexagon-image-30-32"
             {% if account == user.account %}
             data-src="{% static 'img/badge/gold-b.png' %}"
             {% else %}
             data-src="{% static 'img/badge/silver-b.png' %}"
             {% endif %}
        >
        </div>
        <!-- /HEXAGON -->
    </div>
    <!-- /USER AVATAR CONTENT -->

    <!-- USER AVATAR PROGRESS -->
    <div class="user-avatar-progress">
        <!-- HEXAGON -->
        <div class="hexagon-progress-40-44
        {% if account == user.account %}
        logged-account-hexagon-progress-40-44
        {% else %}
        account-color-index-{{account.level|get_color_index_by_level}}-hexagon-progress-40-44
        {% endif %}"></div>
        <!-- /HEXAGON -->
    </div>
    <!-- /USER AVATAR PROGRESS -->

    <!-- USER AVATAR PROGRESS BORDER -->
    <div class="user-avatar-progress-border">
        <!-- HEXAGON -->
        <div class="hexagon-border-40-44"></div>
        <!-- /HEXAGON -->
    </div>
    <!-- /USER AVATAR PROGRESS BORDER -->

    <!-- USER AVATAR BADGE -->
    <div class="user-avatar-badge">
        <!-- USER AVATAR BADGE BORDER -->
        <div class="user-avatar-badge-border">
            <!-- HEXAGON -->
            <div class="hexagon-22-24"></div>
            <!-- /HEXAGON -->
        </div>
        <!-- /USER AVATAR BADGE BORDER -->

        <!-- USER AVATAR BADGE CONTENT -->
        <div class="user-avatar-badge-content">
            <!-- HEXAGON -->
            <div class="hexagon-dark-16-18"></div>
            <!-- /HEXAGON -->
        </div>
        <!-- /USER AVATAR BADGE CONTENT -->

        <!-- USER AVATAR BADGE TEXT -->
        <p class="user-avatar-badge-text">{{ account.level }}</p>
        <!-- /USER AVATAR BADGE TEXT -->
    </div>
    <!-- /USER AVATAR BADGE -->
</div>
<!-- /USER AVATAR -->

templates/includes/diary-widget.html
{% load static %}

<!-- WIDGET BOX -->
<div class="widget-box no-padding mt-2">
    <!-- WIDGET BOX SETTINGS -->
    <div class="widget-box-settings">
        <!-- POST SETTINGS WRAP -->
        <div class="post-settings-wrap">
            <!-- POST SETTINGS -->
            <div class="post-settings widget-box-post-settings-dropdown-trigger">
                <!-- POST SETTINGS ICON -->
                <svg class="post-settings-icon icon-more-dots">
                    <use xlink:href="#svg-more-dots"></use>
                </svg>
                <!-- /POST SETTINGS ICON -->
            </div>
            <!-- /POST SETTINGS -->

            <!-- SIMPLE DROPDOWN -->
            <div class="simple-dropdown widget-box-post-settings-dropdown">
                <!-- SIMPLE DROPDOWN LINK -->
                <a href="{% url 'diaries:detail_view' diary.id %}">
                    <p class="simple-dropdown-link">Detail Page</p>
                </a>
                <!-- /SIMPLE DROPDOWN LINK -->
            </div>
            <!-- /SIMPLE DROPDOWN -->
        </div>
        <!-- /POST SETTINGS WRAP -->
    </div>
    <!-- /WIDGET BOX SETTINGS -->

    <!-- WIDGET BOX STATUS -->
    <div class="widget-box-status" style="
    {% if not diary.commits.count %}background-color: #ff000030; border-radius: 10px{% endif %}">
        <!-- WIDGET BOX STATUS CONTENT -->
        <div class="widget-box-status-content">
            <!-- USER STATUS -->
            <div class="user-status">
                <!-- USER STATUS AVATAR -->
                <a class="user-status-avatar" href="#">
                    <!-- USER AVATAR -->
                    {% include "includes/account-avatar-small.html" with account=diary.account diary=diary %}
                </a>
                <!-- /USER STATUS AVATAR -->

                <!-- USER STATUS TITLE -->
                <div class="user-status-title medium">
                    <a href="{% url 'diaries:detail_view' diary.id %}">
                        {{ diary.account }} - Diary: {{ diary.created_date|date:"d.m.Y" }}
                    </a>
                </div>
                <!-- /USER STATUS TITLE -->

                <!-- USER STATUS TEXT -->
                <p class="user-status-text small">{{ diary.get_earned_xp }} XP earned on this diary</p>
                <!-- /USER STATUS TEXT -->
            </div>
            <!-- /USER STATUS -->

            <!-- QUOTE BOX -->
            {% if diary.commits.last %}
            <a href="{% url 'diaries:detail_view' diary.id %}">
                <blockquote class="quote-box">
                    <!-- QUOTE BOX ICON -->
                    <svg class="quote-box-icon icon-quote">
                        <use xlink:href="#svg-quote"></use>
                    </svg>
                    <!-- /QUOTE BOX ICON -->

                    <!-- QUOTE BOX TEXT -->
                    <p class="quote-box-text">{{ diary.commits.last.message }}</p>
                    <!-- /QUOTE BOX TEXT -->
                </blockquote>
            </a>
            {% endif %}
            <!-- /QUOTE BOX -->

            <!-- QUOTE BOX -->
            {% if diary.comments.last %}
            <a href="{% url 'diaries:detail_view' diary.id %}?on_comments_tab=1">
                <blockquote class="quote-box
                {% if diary.comments_last_read_by and user.account != diary.comments_last_read_by  %}
                    rainbow-animation
                {% endif %}
                " style="background-color: #00e04308;">
                    <!-- QUOTE BOX ICON -->
                    <svg class="quote-box-icon icon-quote">
                        <use xlink:href="#svg-quote"></use>
                    </svg>
                    <!-- /QUOTE BOX ICON -->

                    <!-- QUOTE BOX TEXT -->
                    <p class="quote-box-text">{{ diary.comments.last.author }} : : {{ diary.comments.last.body }}</p>
                    <!-- /QUOTE BOX TEXT -->
                </blockquote>
            </a>
            {% endif %}
            <!-- /QUOTE BOX -->

            <!-- CONTENT ACTIONS -->
            <div class="content-actions">
                <!-- CONTENT ACTION -->
                <div class="content-action">

                    <!-- META LINE -->
                    <div class="meta-line">
                        <!-- RATING LIST -->
                        {% include "includes/rating-list.html" with stars=diary.commits.count %}
                        <!-- /RATING LIST -->
                    </div>
                    <!-- /META LINE -->
                </div>
                <!-- /CONTENT ACTION -->

                <!-- CONTENT ACTION -->
                <div class="content-action">
                    <!-- META LINE -->
                    <div class="meta-line">
                        <!-- META LINE LINK -->
                        <a href="{% url 'diaries:detail_view' diary.id %}" class="meta-line-link">
                            {{ diary.commits.count }} Commits</a>
                        <!-- /META LINE LINK -->
                    </div>
                    <!-- /META LINE -->

                    <!-- META LINE -->
                    <div class="meta-line">
                        <!-- META LINE TEXT -->
                        <a href="{% url 'diaries:detail_view' diary.id %}?on_comments_tab=1" class="meta-line-text">
                            {{ diary.comments.count }} Comments</a>
                        <!-- /META LINE TEXT -->
                    </div>
                    <!-- /META LINE -->
                </div>
                <!-- /CONTENT ACTION -->
            </div>
            <!-- /CONTENT ACTIONS -->
        </div>
        <!-- /WIDGET BOX STATUS CONTENT -->
    </div>
    <!-- /WIDGET BOX STATUS -->

    <!-- POST OPTIONS --><!-- /POST OPTIONS -->
</div>
<!-- /WIDGET BOX -->

templates/includes/pager-bar.html
{% if objects.has_other_pages %}
<div class="section-pager-bar-wrap align-right">
    <!-- SECTION PAGER BAR -->
    <div class="section-pager-bar" style="min-width: 355px; max-width: 406px">

        <!-- SECTION PAGER -->
        <div class="section-pager">
            <!-- SECTION PAGER ITEM -->
            {% for page in objects.paginator.page_range %}
                {% if page == objects.number %}
                <a href="#">
                    <div class="section-pager-item active">
                        <!-- SECTION PAGER ITEM TEXT -->
                        <p class="section-pager-item-text">{{ page }}</p>
                        <!-- /SECTION PAGER ITEM TEXT -->
                    </div>
                </a>
                {% elif page > objects.number|add:'-3' and page < objects.number|add:'3' %}
                <a href="?page={{ page }}&page_size={{ request.GET.page_size }}">
                    <div class="section-pager-item">
                        <!-- SECTION PAGER ITEM TEXT -->
                        <p class="section-pager-item-text">{{ page }}</p>
                        <!-- /SECTION PAGER ITEM TEXT -->
                    </div>
                </a>
                {% endif %}
            {% endfor %}
            <!-- /SECTION PAGER ITEM -->
        </div>
        <!-- /SECTION PAGER -->

        <!-- SECTION PAGER CONTROLS -->
        <div class="section-pager-controls">
            {% if objects.has_previous %}
            <!-- SLIDER CONTROL -->
            <a href="?page=1&page_size={{ request.GET.page_size }}">
                <div class="slider-control left">
                    <!-- SLIDER CONTROL ICON -->
                    <svg class="slider-control-icon icon-small-arrow">
                        <use xlink:href="#svg-small-arrow"></use>
                    </svg>
                    <!-- /SLIDER CONTROL ICON -->
                </div>
            </a>
            <!-- /SLIDER CONTROL -->
            {% endif %}

            {% if objects.has_next %}
            <!-- SLIDER CONTROL -->
            <a href="?page={{ objects.paginator.num_pages }}&page_size={{ request.GET.page_size }}">
                <div class="slider-control right">
                    <!-- SLIDER CONTROL ICON -->
                    <svg class="slider-control-icon icon-small-arrow">
                        <use xlink:href="#svg-small-arrow"></use>
                    </svg>
                    <!-- /SLIDER CONTROL ICON -->
                </div>
            </a>
            <!-- /SLIDER CONTROL -->
            {% endif %}

        </div>
        <!-- /SECTION PAGER CONTROLS -->
    </div>
    <!-- /SECTION PAGER BAR -->
</div>
{% endif %}

templates/includes/rating-list.html
<div class="rating-list">

    <!-- RATING -->
    <div class="rating dark {% if stars >= 1 %} filled {% endif %}">
        <!-- RATING ICON -->
        <svg class="rating-icon icon-star">
            <use xlink:href="#svg-star"></use>
        </svg>
        <!-- /RATING ICON -->
    </div>
    <!-- /RATING -->

    <!-- RATING -->
    <div class="rating dark {% if stars >= 2 %} filled {% endif %}">
        <!-- RATING ICON -->
        <svg class="rating-icon icon-star">
            <use xlink:href="#svg-star"></use>
        </svg>
        <!-- /RATING ICON -->
    </div>
    <!-- /RATING -->

    <!-- RATING -->
    <div class="rating dark {% if stars >= 3 %} filled {% endif %}">
        <!-- RATING ICON -->
        <svg class="rating-icon icon-star">
            <use xlink:href="#svg-star"></use>
        </svg>
        <!-- /RATING ICON -->
    </div>
    <!-- /RATING -->

    <!-- RATING -->
    <div class="rating dark {% if stars >= 4 %} filled {% endif %}">
        <!-- RATING ICON -->
        <svg class="rating-icon icon-star">
            <use xlink:href="#svg-star"></use>
        </svg>
        <!-- /RATING ICON -->
    </div>
    <!-- /RATING -->

    <!-- RATING -->
    <div class="rating dark {% if stars >= 5 %} filled {% endif %}">
        <!-- RATING ICON -->
        <svg class="rating-icon icon-star">
            <use xlink:href="#svg-star"></use>
        </svg>
        <!-- /RATING ICON -->
    </div>
    <!-- /RATING -->
</div>