apps/authentication/urls.py
from django.urls import path

from . import views
from . import interactors


app_name = "authentication"


# Views

urlpatterns = [
    path("authentication-view/", views.authentication, name="authentication_view"),
]

# Interactors

urlpatterns += [
    path("signup/", interactors.signup, name="signup"),
    path("signin/", interactors.signin, name="signin"),
    path("signout/", interactors.signout, name="signout"),
]

rp2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


def default_view(request):
    return redirect("clans:overview")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("authentication/", include("apps.authentication.urls", namespace="authentication")),
    path("accounts/", include("apps.accounts.urls", namespace="accounts")),
    path("issues/", include("apps.issues.urls", namespace="issues")),
    path("clans/", include("apps.clans.urls", namespace="clans")),
    path("diaries/", include("apps.diaries.urls", namespace="diaries")),
    path("", default_view),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/authentication/models.py
from django.db import models

# Create your models here.

apps/authentication/views.py
from django.shortcuts import render


def authentication(request):
    return render(request, "authentication/authentication.html")

templates/authentication/authentication.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- bootstrap 4.3.1 -->
  <link rel="stylesheet" href="{% static 'css/vendor/bootstrap.min.css' %}">
  <!-- styles -->
  <link rel="stylesheet" href="{% static 'css/styles.min.css' %}">
  <!-- favicon -->
  <link rel="icon" href="{% static 'img/favicon.ico' %}">
  <title>RP2 | Authentication</title>
</head>
<body>

  <!-- LANDING -->
  <div class="landing">
    <!-- LANDING DECORATION -->
    <div class="landing-decoration"></div>
    <!-- /LANDING DECORATION -->

    <!-- LANDING INFO -->
    <div class="landing-info">
      <!-- LOGO -->
      <div class="logo">
        <!-- ICON LOGO VIKINGER -->
        <svg class="icon-logo-vikinger">
          <use xlink:href="#svg-logo-vikinger"></use>
        </svg>
        <!-- /ICON LOGO VIKINGER -->
      </div>
      <!-- /LOGO -->

      <!-- LANDING INFO PRETITLE -->
      <h2 class="landing-info-pretitle">Welcome to</h2>
      <!-- /LANDING INFO PRETITLE -->

      <!-- LANDING INFO TITLE -->
      <h1 class="landing-info-title">Rysgally Project 2</h1>
      <!-- /LANDING INFO TITLE -->

      <!-- LANDING INFO TEXT -->
      <p class="landing-info-text">Next generation project and task management system! Work with your team members and interact with the gamification system!</p>
      <!-- /LANDING INFO TEXT -->

      <!-- TAB SWITCH -->
      <div class="tab-switch">
        <!-- TAB SWITCH BUTTON -->
        <p class="tab-switch-button login-register-form-trigger">Signin</p>
        <!-- /TAB SWITCH BUTTON -->

        <!-- TAB SWITCH BUTTON -->
        <p class="tab-switch-button login-register-form-trigger">Signup</p>
        <!-- /TAB SWITCH BUTTON -->
      </div>
      <!-- /TAB SWITCH -->
    </div>
    <!-- /LANDING INFO -->

    <!-- LANDING FORM -->
    <div class="landing-form">
      <!-- FORM BOX -->
      <div class="form-box login-register-form-element">
        <!-- FORM BOX DECORATION -->
        <img class="form-box-decoration overflowing" src="{% static 'img/landing/rocket.png' %}" alt="rocket">
        <!-- /FORM BOX DECORATION -->

        <!-- FORM BOX TITLE -->
        <h2 class="form-box-title">Account Login</h2>
        <!-- /FORM BOX TITLE -->

        {% for message in messages %}
          <p class="badge-item-stat-text pt-3 text-center text-danger">{{ message }}</p>
        {% endfor %}

        <!-- FORM -->
        <form class="form" action="{% url 'authentication:signin' %}" method="POST">
          {% csrf_token %}
          <!-- FORM ROW -->
          <div class="form-row">
            <!-- FORM ITEM -->
            <div class="form-item">
              <!-- FORM INPUT -->
              <div class="form-input">
                <label for="signin_username">
                  {% if not request.GET.username %} Username {% endif %}
                </label>
                <input
                    required
                    type="text"
                    id="signin_username"
                    name="signin_username"
                    value="{{ request.GET.username }}"
                >
              </div>
              <!-- /FORM INPUT -->
            </div>
            <!-- /FORM ITEM -->
          </div>
          <!-- /FORM ROW -->
    
          <!-- FORM ROW -->
          <div class="form-row">
            <!-- FORM ITEM -->
            <div class="form-item">
              <!-- FORM INPUT -->
              <div class="form-input">
                <label for="signin_password">Password</label>
                <input type="password" id="signin_password" name="signin_password" required>
              </div>
              <!-- /FORM INPUT -->
            </div>
            <!-- /FORM ITEM -->
          </div>
          <!-- /FORM ROW -->
    
          <!-- FORM ROW -->
          <div class="form-row">
            <!-- FORM ITEM -->
            <div class="form-item">
              <!-- BUTTON -->
              <button type="submit" class="button medium secondary">Signin to your Account!</button>
              <!-- /BUTTON -->
            </div>
            <!-- /FORM ITEM -->
          </div>
          <!-- /FORM ROW -->
        </form>
        <!-- /FORM -->
    
        <!-- LINED TEXT --><!-- /LINED TEXT -->
        <!-- SOCIAL LINKS --><!-- /SOCIAL LINKS -->
      </div>
      <!-- /FORM BOX -->
    
      <!-- FORM BOX -->
      <div class="form-box login-register-form-element">
        <!-- FORM BOX DECORATION -->
        <img class="form-box-decoration" src="{% static 'img/landing/rocket.png' %}" alt="rocket">
        <!-- /FORM BOX DECORATION -->

        <!-- FORM BOX TITLE -->
        <h2 class="form-box-title">Create your Account!</h2>
        <!-- /FORM BOX TITLE -->
    
        <!-- FORM -->
        <form class="form" action="{% url 'authentication:signup' %}" method="POST">
          {% csrf_token %}

          <!-- FORM ROW -->
          <div class="form-row">
            <!-- FORM ITEM -->
            <div class="form-item">
              <!-- FORM INPUT -->
              <div class="form-input">
                <label for="signup_username">
                  {% if not request.GET.username %} Username {% endif %}
                </label>
                <input
                    required
                    type="text"
                    id="signup_username"
                    name="signup_username"
                    value="{{ request.GET.username }}"
                >
              </div>
              <!-- /FORM INPUT -->
            </div>
            <!-- /FORM ITEM -->
          </div>
          <!-- /FORM ROW -->

          <!-- FORM ROW -->
          <div class="form-row">
            <!-- FORM ITEM -->
            <div class="form-item">
              <!-- FORM INPUT -->
              <div class="form-input">
                <label for="signup_password">Password</label>
                <input type="text" id="signup_password" name="signup_password" required>
              </div>
              <!-- /FORM INPUT -->
            </div>
            <!-- /FORM ITEM -->
          </div>
          <!-- /FORM ROW -->

          <!-- FORM ROW -->
          <div class="form-row">
            <!-- FORM ITEM -->
            <div class="form-item">
              <!-- FORM INPUT -->
              <div class="form-input">
                <label for="signup_repeat_password">Repeat Password</label>
                <input type="text" id="signup_repeat_password" name="signup_repeat_password" required>
              </div>
              <!-- /FORM INPUT -->
            </div>
            <!-- /FORM ITEM -->
          </div>
          <!-- /FORM ROW -->

          <!-- FORM ROW -->
          <div class="form-row">
            <!-- FORM ITEM -->
            <div class="form-item">
              <!-- FORM INPUT -->
              <div class="form-input">
                <label for="signup_first_name">First Name</label>
                <input type="text" id="signup_first_name" name="signup_first_name">
              </div>
              <!-- /FORM INPUT -->
            </div>
            <!-- /FORM ITEM -->
          </div>
          <!-- /FORM ROW -->

          <!-- FORM ROW -->
          <div class="form-row">
            <!-- FORM ITEM -->
            <div class="form-item">
              <!-- FORM INPUT -->
              <div class="form-input">
                <label for="signup_last_name">Last Name</label>
                <input type="text" id="signup_last_name" name="signup_last_name">
              </div>
              <!-- /FORM INPUT -->
            </div>
            <!-- /FORM ITEM -->
          </div>
          <!-- /FORM ROW -->
    
          <!-- FORM ROW -->
          <div class="form-row">
            <!-- FORM ITEM -->
            <div class="form-item">
              <!-- BUTTON -->
              <button type="submit" class="button medium primary">Signup Now!</button>
              <!-- /BUTTON -->
            </div>
            <!-- /FORM ITEM -->
          </div>
          <!-- /FORM ROW -->
        </form>
        <!-- /FORM -->

      </div>
      <!-- /FORM BOX -->
    </div>
    <!-- /LANDING FORM -->
  </div>
  <!-- /LANDING -->

<!-- app -->
<script src="{% static 'js/utils/app.js' %}"></script>
<!-- XM_Plugins -->
<script src="{% static 'js/vendor/xm_plugins.min.js' %}"></script>
<!-- form.utils -->
<script src="{% static 'js/form/form.utils.js' %}"></script>
<!-- landing.tabs -->
<script src="{% static 'js/landing/landing.tabs.js' %}"></script>
<!-- SVG icons -->
<script src="{% static 'js/utils/svg-loader.js' %}"></script>
</body>
</html>